project:
  type: website
  output-dir: docs
  resources:
    - keybase.txt
    - resume.pdf
    - cv.pdf

website:
  title: "Alex Cebulski"
  site-url: https://acebulsk.github.io
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@alex_snow_hydro"
  comments:
    utterances:
      repo: acebulsk/acebulsk.github.io
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Papers"
        href: papers
      - text: "Presentations"
        href: presentations
      - text: "Blog"
        href: blog.html
format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
