[[redirects]]
  from = "/orcid"
  to = "https://orcid.org/0000-0003-2402-304X"
  
[[redirects]]
  from = "/github"
  to = "https://github.com/mikemahoney218"
  
[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/mikemahoney218/"
  
[[redirects]]
  from = "/researchgate"
  to = "https://www.researchgate.net/profile/Michael_Mahoney13"

[[redirects]]
  from = "/twitter"
  to = "https://www.twitter.com/mikemahoney218"

[[redirects]]
  from = "/cv"
  to = "/cv.pdf"

[[redirects]]
  from = "/resume"
  to = "/resume.pdf"
  
[[redirects]]
  from = "/quotes"
  to = "/quotes/index.html"
  
[[redirects]]
  from = "/2020/04/mechanics-of-viz"
  to = "/posts/2020/04/mechanics-of-viz"
  
[[redirects]]
  from = "/2020/05/tig-on-pi"
  to = "/posts/2020/05/tig-on-pi"
  
[[redirects]]
  from = "/2020/04/theory-of-data-viz"
  to = "/posts/2020/04/theory-of-data-viz"
  
[[redirects]]
  from = "/2020/04/making-excellent-viz"
  to = "/posts/2020/04/making-excellent-viz"
  
  [[redirects]]
  from = "/blog/2020/04/mechanics-of-viz"
  to = "/posts/2020/04/mechanics-of-viz"
  
[[redirects]]
  from = "/blog/2020/05/tig-on-pi"
  to = "/posts/2020/05/tig-on-pi"
  
[[redirects]]
  from = "/blog/2020/04/theory-of-data-viz"
  to = "/posts/2020/04/theory-of-data-viz"
  
[[redirects]]
  from = "/blog/2020/04/making-excellent-viz"
  to = "/posts/2020/04/making-excellent-viz"

