---
title: Conference Presentations
comments: false
---

**Cebulski, A.** and Pomeroy, J.W. (2024). Effect of Wind, Hydrometeor Fall Velocity and Canopy Structure on Snow Interception in a Windswept Subalpine Environment. Canadian Geophysical Union Meeting. Ottawa, Ontario. (Oral Presentation, Regional Conference, PhD work).

Harasyn, M.L., Harder, P.H., **Cebulski, A.**, Lehan, K., Koslowsky, H., Fang, X., Pomeroy, J.W. (2024). Methods of calculating snow water equivalent from drone-based lidar over a high mountain basin. Canadian Geophysical Union Meeting. Ottawa, Ontario. (Oral Presentation, Regional Conference, PhD work).

**Cebulski, A.** and Pomeroy, J.W. (2023). The Influence of Meteorology on Snow Interception Processes. American Geophysical Union Meeting. San Francisco, California. (Poster Presentation, International Conference, PhD work).

**Cebulski, A.** and Pomeroy, J.W. (2023). The Influence of Meteorology on Canopy Snow Ablation. The International Network for Alpine Research Catchment Hydrology (INARCH) Workshop. Boise, Idaho. (Oral Presentation, International Conference, PhD work).

**Cebulski, A.** and Pomeroy, J.W. (2023). New Observations of Snow Interception Processes in a Windswept Subalpine Environment. Global Water Futures Annual Science Meeting. Saskatoon, Saskatchewan. (Poster Presentation, Regional Conference, PhD work).

**Cebulski, A.** and Pomeroy, J.W. (2023). Snow Interception Processes and Prediction in a Windswept Subalpine Environment. Canadian Geophysical Union Meeting. Banff, Alberta. (Oral Presentation, Regional Conference, PhD work).

Harasyn, M.L., **Cebulski, A.**, Lehan, K., Koslowsky, H., Harder, P.H., Pomeroy, J.W. (2023). Comparison of in situ and drone-based lidar snow depth measurements in a forested subalpine region. Canadian Geophysical Union Meeting. Ottawa, Ontario. (Oral Presentation, Regional Conference, PhD work).

Pomeroy, J.W. and **Cebulski, A.** (2022). Wither Sublimation? Lower Sublimation Losses with Climate Warming Due to Suppression of Blowing Snow Transport and Forest Snow Interception Processes. American Geophysical Union Meeting. Chicago, Illinois. (Oral Presentation, International Conference, PhD work).

Bisset, R., Floyd, W.C., Menounos, B., Bishop, A., **Cebulski, A.**, Fisk, G. Marchenko, S., Marshall, P. (2022). Quantifying Spatio-Temporally Distributed Snow Density across Four Forested Mountain Watersheds in South-Western British Columbia. American Geophysical Union Meeting. Chicago, Illinois. (Oral Presentation, International Conference, work at VIU).

**Cebulski, A.** and Pomeroy, J.W. (2022). Snow Interception Processes and Prediction in a Windswept Subalpine Environment. International Glaciological Society - International Symposium on Snow. Davos, Switzerland. (Oral Presentation, International Conference, PhD work).

Butman, D., McNicol, G., Giesbrecht, I., Tank, S., Hood, E.W., Floyd, W.C., Lung, J.L., D'Amore, D., McSorely, H., **Cebulski, A.**, Trubilowicz, J.W., Oliver, A., Fylpaa, C., Fellman, J., Frazer, G.W., Lally, A., Arriola, S.G. (2020). Carbon Export from the Pacific Northwest Coastal Rainforest Margin. American Geophysical Union Meeting. Online. (Poster Presentation, International Conference, work at VIU).

Floyd, B.C., McInnes, W., Holmes, K., **Cebulski, A.**, Dickinson, T., Butler, S., Heathfield, D., Menounos, B. (2019). Application of UAVs to measure snowpack using structure from motion analysis over varying terrain and vegetation in Coastal British Columbia. American Geophysical Union Meeting. San Francisco, California. (Oral Presentation, International Conference, work at VIU)

**Cebulski, A.**, Floyd, B.C., Trubilowicz, J W., D'Amore, D., Bidlack, A. (2019). Quantifying freshwater discharge into the Pacific Ocean from southeast Alaska to northern California using a distributed hydrological model. MABRRI Regional Research Conference. Parksville, British Columbia. (Oral Presentation, Regional Conference, work at VIU)

**Cebulski, A.**, Desloges, J.R. (2018). The Glaciolacustrine Sediment Record of Cariboo Lake, BC: Implications for Holocene Fluvial and Glacial Watershed Dynamics. Joint meeting of the Canadian and American Quaternary Associations. Ottawa, Ontario. (Oral Presentation, International Conference, MSc work)

**Cebulski, A.**, Enanga, E., Creed, I (2016). Quantifying the Carbon Sequestration of Restored Wetlands in the Agricultural Landscape of Southern Ontario. World Wetland Day Conference. Waterloo, Ontario. (Poster Presentation, International Conference, BSc work)
