---
title: Papers
comments: false
---

## Published 

**Cebulski, A.** and Pomeroy, J.W. (2026). Processes Governing the Ablation of Intercepted Snow. *Water Resources Research, 62*(2), e2025WR042009. [[https://doi.org/10.1002/hyp.70135]](https://doi.org/10.1029/2025WR042009)

**Cebulski, A.** and Pomeroy, J.W. (2025). Snow Interception Relationships With Meteorology and Canopy Density. *Hydrological Processes, 39*(4), e70135. [[https://doi.org/10.1002/hyp.70135]](https://doi.org/10.1002/hyp.70135)

**Cebulski, A.** and Pomeroy, J.W. (2025). The Theoretical Underpinnings of Snow Interception and Ablation Parameterizations. *WIREs Water, 12*, e70010. [[https://doi.org/10.1002/wat2.70010]](https://doi.org/10.1002/wat2.70010)

**Cebulski, A.** and Desloges, J.R. (2024). The Influence of Fluvial and Glacial Watershed Dynamics on Holocene Sediment Accumulation in Cariboo Lake, Columbia Mountains, British Columbia, Canada. *Canadian Journal of Earth Sciences, 61*(4): 543-559. [[https://doi.org/10.1139/cjes-2023-0094]](https://doi.org/10.1139/cjes-2023-0094)

McNicol, G., Hood, E., Butman, D.E., Tank, S.E., Giesbrecht, I., Floyd, W.C., D'Amore, D., Fellman, J.B., **Cebulski, A.**, Lally, A., McSorley, H., and Arriola, S.G. (2023). Small, coastal temperate rainforest watersheds dominate dissolved organic carbon transport to the northeast Pacific Ocean. *Geophysical Research Letters, 50*, e2023GL103024. [[https://doi.org/10.1029/2023GL103024]](https://doi.org/10.1029/2023GL103024)

<!-- ## In Preparation -->

<!-- Bisset, R., Floyd, W., Menounos, B., Bishop, A., Marchenko, S., Fisk, G., **Cebulski, A.**, Marshall, P., Heathfield, D., Beffort, S., White, R., Arriola, S.G., Viner, N. (submitted, in review). Snow water storage within eight Pacific Coastal watersheds in British Columbia (Canada) inferred from four years of aerial LiDAR data. *Water Resources Research*. -->

<!-- **Cebulski, A.** and Pomeroy, J.W. (in prep.). The Influence of Meteorology on Canopy Snow Ablation Processes. *Water Resources Research*. -->

<!-- **Cebulski, A.** and Pomeroy, J.W. (in prep.). An Evaluation of New Snow Interception and Ablation Parameterizations in Three Mountain Forests in western Canada. *Water Resources Research*. -->

<!-- Oogathoo, S., Pomeroy, J., Pietroniro, A., Petrone, R., **Cebulski, A.** (in prep.). Evaluating energy fluxes and snow processes at mountain subalpine forest and alpine tundra sites using MESH. *Hydrology and Earth System Sciences*. -->
